In [1]:
import numpy as np
import pandas as pd

# import matplotlib.pyplot as plt
# import seaborn as sns

from datetime import date, datetime, timedelta

import os

# Задание 1. Сессии

## Условие

Есть данные следующего вида:

In [2]:
sessions = pd.read_csv('./data/sessions.csv')

sessions

    user_id       event_datetime  duration_sec
0         1  2023-10-01 15:12:06           234
1         2  2023-10-01 23:43:17           187
2         2  2023-10-22 11:12:00            87
3         1  2023-11-15 15:12:24             3
4         1  2023-12-12 00:17:06            28
5         1  2023-12-14 00:25:06           465
6         3  2023-10-05 08:45:30           120
7         2  2023-11-01 14:22:10           300
8         3  2023-11-10 09:15:45           150
9         1  2023-11-20 16:30:00           200
10        2  2023-12-01 12:00:00           400
11        3  2023-12-05 18:45:30           180
12        4  2023-12-05 18:45:30             1

Необходимо написать такой SQL запрос, который выведет пользователя с максимальным промежутком между сессиями. Синтаксис - **Clickhouse SQL**.

## Решение

### Старое

In [3]:
# os.system("curl https://clickhouse.com/ | sh")

query = """
with
    src as (
        select
            user_id,
            event_datetime                           as session_datetime
            --addSeconds(event_datetime, duration_sec) as session_datetime
        from file('./data/sessions.csv', CSVWithNames) as sns
        where
            duration_sec > 0 --Assume it a check for a legit session.
        group by
            1, 2
        order by
            1, 2
    ),

    final as (
        select
            user_id,

            groupArray(session_datetime)           as dt_arr,
            arrayPopFront(arrayDifference(dt_arr)) as diff_arr,
            
            --arrayMax(diff_arr)                     as agg_diff, --1
            --arrayAvg(diff_arr)                     as agg_diff, --3
            --arrayReduce('median', diff_arr)        as agg_diff, --3
            --arraySum(diff_arr)                     as agg_diff, --1
            arrayMin(diff_arr)                     as agg_diff, --3

            row_number() over (
                order by agg_diff desc, user_id asc
            )                                      as rn
        from src
        group by
            1
    )

select user_id
from final
where rn = 1
format CSVWithNames
"""

cmd = """
./clickhouse local -q "
{}
"
""".format(query)
 # > result.csv

os.system(cmd)

"user_id"
3

0

Решение через AWS Redshift строилось бы на
```
lead(event_datetime) over (
    partition by user_id
    order by event_datetime
) as next_event_datetime
```

Но учитывая, что необходимо использовать синтаксис __ClickHouse__, решаем через массивы:
1. Фильтруем невалидные значения, дедуплицируем и сортируем timestamps для будущего массива.
    1. `event_datetime` может быть либо концом ивента (тогда для `session_datetime` просто берем `event_datetime`), либо его началом (тогда добавляем к нему `duration_sec`). На тестовых данных ответы одинаковы.
3. Собираем массив, трансформируем его в first differences (без нулевого/первого 0), применяем агрегатную функцию поверх:
    1. Задача требует "пользователя с __максимальным промежутком между сессиями__", так что берём `max()` среди всех промежутков между сессиями одного пользователя.
    2. Возможны и другие осмысленные агрегации (для слегка по-другому сформулированной задачи: "__максимальным__ _средним/медианным/суммарным/или_даже_минимальным_ промежутком между сессиями"), в комментариях указан результат для них на тестовых данных.
4. Ранжируем по значению агрегата по убыванию: можно использовать `rank()` вместо `row_number()` (на случай ничьей), но в задаче требуется вывести "__пользователя__ с максимальным промежутком между сессиями", так что обеспечим единственность с помощью `row_number()`, а стабильность расчета дополнительным `order by user_id`.

### Новое

>в 1 задаче можно исправить недочет

>формулировка вопроса - время между сессиями. duration_sec там не просто так

>event_datetime - начало сессии \
>код для этой версии - не верный \
>нужно время МЕЖДУ двумя сессиями

In [4]:
# os.system("curl https://clickhouse.com/ | sh")

query = """
with
    src as (
        select
            user_id,
            event_datetime                       as cur_session_start,
            
            max(addSeconds(
                cur_session_start,
                duration_sec
            ))                                   as cur_session_end,
            leadInFrame(event_datetime) over (
                partition by user_id
                order by event_datetime asc
                rows between unbounded preceding and unbounded following
            )                                    as next_session_start,
            
            next_session_start - cur_session_end as time_between_sessions
        from file('./data/sessions.csv', CSVWithNames) as sns
        where
            duration_sec > 0 --Assume it a check for a legit session.
        group by
            1, 2
    ),

    final as (
        select
            user_id,

            max(time_between_sessions) as agg_tbs, --1
            --min(time_between_sessions) as agg_tbs, --3
            --avg(1.0 * time_between_sessions) as agg_tbs, --3
            --median(time_between_sessions) as agg_tbs, --3
            --sum(time_between_sessions) as agg_tbs, --1
            
            row_number() over (
                order by agg_tbs desc, user_id asc
            )                          as rn
        from src
        group by
            1
    )

select user_id
from final
where rn = 1
format CSVWithNames
"""

cmd = """
./clickhouse local -q "
{}
"
""".format(query)
 # > result.csv

os.system(cmd)

"user_id"
1

0

__Исправление:__ промежуток между сессиями вычисляется как разница между концом текущей и началом следующей.
- `event_datetime` — начало сессии.
- `event_datetime + duration_src` — конец сессии.

В таком случае несмотря на то, что синтаксис __ClickHouse__, используем `lead()` (разве что придётся использовать неловкую конструкцию `leadInFrame() over (... rows between unbounded preceding and unbounded following)`).

Комментарии об осмысленной аггрегации и ранжирование те же, что и в прошлом решении.

# Задание 2. Аномалии

## Условие

Есть данные с платежами пользователей следующего вида:

In [5]:
bills = pd.read_csv(
    './data/bills.csv',
    parse_dates=['event_datetime'],
    dtype={
        'payment_method': 'category',
        'country': 'category',
        'status': 'category'
    }
)

bills.head()

,event_datetime,user_id,payment_method,country,amount,status
0,2022-12-01 00:00:00.000000000,9543706,card_processing,AE,10.90,success
1,2022-12-01 00:00:02.592002592,9835632,binance_pay,SA,71.43,cancel
2,2022-12-01 00:00:05.184005184,7526368,card_processing,SA,18.44,cancel
3,2022-12-01 00:00:07.776007776,4572510,card_processing,SA,40.91,cancel
4,2022-12-01 00:00:10.368010368,7832872,binance_pay,SA,23.00,cancel

Полный сэмпл данных в приложенном CSV файле.

Нужно исследовать данные и найти случаи, когда были проблемы с одним или несколькими платежными методами.

Ответ можно предоставить в виде Jupyter Notebook .ipynb файла

## Решение

### Код

In [6]:
bills.info() #No nulls, good.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   event_datetime  1000000 non-null  datetime64[ns]
 1   user_id         1000000 non-null  int64
 2   payment_method  1000000 non-null  category
 3   country         1000000 non-null  category
 4   amount          1000000 non-null  float64
 5   status          1000000 non-null  category
dtypes: category(3), datetime64[ns](1), float64(1), int64(1)
memory usage: 25.8 MB

In [7]:
bills.describe()

                      event_datetime       user_id          amount
count                        1000000  1.000000e+06  1000000.000000
mean   2022-12-15 23:59:59.999995904  5.491539e+06       50.935791
min              2022-12-01 00:00:00  1.000021e+06       10.000000
25%              2022-12-08 12:00:00  3.251441e+06       14.390000
50%              2022-12-16 00:00:00  5.484437e+06       34.680000
75%              2022-12-23 12:00:00  7.725785e+06       69.400000
max              2022-12-31 00:00:00  9.999985e+06      815.130000
std                              NaN  2.590692e+06       49.159379

In [8]:
bills.groupby('status', observed=False)['amount'].describe() #All similar apart from pending max.

            count       mean        std   min    25%    50%    75%     max
status
cancel   495339.0  50.910096  49.249934  10.0  14.37  34.64  69.34  815.13
pending  156473.0  51.002809  49.126434  10.0  14.39  34.82  69.65  622.05
success  348188.0  50.942226  49.045215  10.0  14.42  34.68  69.39  811.84

In [9]:
bills.groupby('payment_method', observed=False)['amount'].describe() #All similar apart from max-es.

,count,mean,std,min,25%,50%,75%,max
payment_method,,,,,,,,
binance_pay,184078.0,51.005748,49.378256,10.0,14.3700,34.650,69.5000,700.36
card_processing,547390.0,50.877178,49.069210,10.0,14.4000,34.670,69.2700,815.13
jazzcash,57885.0,50.969278,49.336681,10.0,14.4100,34.630,69.3700,591.93
nagad,32965.0,50.950174,49.148393,10.0,14.3000,34.740,69.3800,456.98
paytm,32736.0,50.957367,49.051354,10.0,14.4000,34.805,69.6900,622.05
pix,26950.0,51.337406,49.654032,10.0,14.4100,34.830,69.9700,526.34
skrill,99472.0,50.947755,49.057809,10.0,14.4275,34.800,69.5000,583.69
upi,18524.0,51.155713,49.123222,10.0,14.3000,34.610,70.4625,496.68

In [10]:
bills.groupby('country', observed=False)['amount'].describe() #Same.

            count       mean        std   min      25%    50%      75%     max
country
AE       200510.0  50.873197  48.969078  10.0  14.3600  34.60  69.4600  583.22
BD        79526.0  50.991196  49.398827  10.0  14.3100  34.59  69.2975  700.36
BR        50947.0  51.249549  49.650889  10.0  14.4700  34.89  69.7450  556.75
IN        99048.0  50.855936  48.879063  10.0  14.3400  34.63  69.4925  811.84
PK       119387.0  50.907120  49.213584  10.0  14.3700  34.64  69.3800  606.68
SA       400128.0  50.961179  49.200333  10.0  14.4100  34.74  69.3500  815.13
TR        30176.0  50.953652  49.407529  10.0  14.5300  34.62  69.5300  542.41
ZA        20278.0  50.580435  48.724144  10.0  14.3825  34.71  68.8700  539.65

In [11]:
bills_stats = (
    bills
    .groupby(['country', 'payment_method', 'status'], observed=True)
    ['amount'].describe()
    .reset_index()
    .sort_values(['country', 'payment_method', 'status'])
)

pd.options.display.max_rows = bills_stats.shape[0]
bills_stats

,country,payment_method,status,count,mean,std,min,25%,50%,75%,max
0,AE,binance_pay,cancel,46882.0,51.000850,49.114783,10.00,14.4300,34.740,69.6300,515.48
1,AE,card_processing,cancel,60228.0,50.426908,48.540011,10.00,14.3600,34.250,68.7525,575.57
2,AE,card_processing,pending,595.0,51.665328,48.709630,10.00,14.1550,34.630,71.3900,300.08
3,AE,card_processing,success,69234.0,51.105877,49.233498,10.00,14.2300,34.710,69.7900,550.82
4,AE,skrill,pending,21507.0,51.056879,49.107822,10.00,14.5950,34.880,70.0300,583.22
5,AE,skrill,success,2064.0,51.049283,47.810847,10.00,14.8100,35.550,68.9725,318.25
6,BD,binance_pay,cancel,9781.0,50.998183,49.757583,10.00,14.3500,34.210,68.5900,700.36
7,BD,binance_pay,pending,16.0,43.140000,40.152011,10.00,10.0000,37.550,56.4875,141.94
8,BD,binance_pay,success,1089.0,53.123747,50.721211,10.00,12.1900,36.320,74.9600,414.09
9,BD,card_processing,cancel,14005.0,51.188492,50.168675,10.00,14.0600,34.670,69.7000,523.29
10,BD,card_processing,pending,119.0,51.263529,49.299989,10.00,13.7850,36.020,70.8800,369.80
11,BD,card_processing,success,16108.0,50.691772,48.857772,10.00,14.5100,34.295,68.7925,460.99
12,BD,nagad,pending,31445.0,50.981948,49.189687,10.00,14.4100,34.790,69.2300,456.98
13,BD,nagad,success,1520.0,50.292855,48.297416,10.00,12.0225,32.800,71.5700,325.20
14,BD,skrill,pending,4979.0,51.157271,49.734220,10.00,14.4950,34.740,69.4000,496.26
15,BD,skrill,success,464.0,51.611746,48.599060,10.00,14.7200,36.225,72.4825,306.83
16,BR,binance_pay,cancel,5063.0,51.263182,49.552208,10.00,15.2400,35.490,68.3750,525.14
17,BR,binance_pay,pending,6.0,39.086667,37.712258,10.00,10.2700,20.975,66.8250,93.76
18,BR,binance_pay,success,516.0,49.078915,47.295952,10.00,14.8300,30.570,65.7675,274.80
19,BR,card_processing,cancel,7272.0,50.841902,50.056127,10.00,14.2475,34.250,69.4600,507.37
20,BR,card_processing,pending,65.0,45.668769,42.816937,10.00,13.1900,30.910,59.3200,222.40
21,BR,card_processing,success,8272.0,50.736142,48.675936,10.00,14.5650,34.855,69.0350,556.75
22,BR,pix,cancel,12079.0,52.085638,50.021140,10.00,14.6950,35.100,71.2150,399.02
23,BR,pix,pending,641.0,52.113229,47.215413,10.00,15.3300,39.040,72.0000,344.81
24,BR,pix,success,14230.0,50.667329,49.441715,10.00,14.1025,34.355,69.1150,526.34
25,BR,skrill,pending,2560.0,53.549172,51.668748,10.00,14.6350,37.540,73.4875,530.42
26,BR,skrill,success,243.0,53.073786,56.528934,10.00,12.9500,32.240,71.6850,324.61
27,IN,card_processing,cancel,18914.0,51.134812,49.026740,10.00,14.6125,35.060,69.4000,490.04
28,IN,card_processing,pending,173.0,48.545202,41.504426,10.00,17.2600,38.350,62.8200,240.39
29,IN,card_processing,success,21345.0,50.299510,48.621902,10.00,14.1000,34.030,68.7200,811.84
30,IN,paytm,cancel,7020.0,51.010887,49.364404,10.00,14.3725,34.775,69.7250,476.13
31,IN,paytm,pending,15780.0,51.374132,49.197522,10.00,14.4000,35.335,70.5775,622.05
32,IN,paytm,success,9936.0,50.257662,48.591948,10.00,14.4100,34.035,68.2525,483.15
33,IN,skrill,pending,6734.0,50.386726,47.890218,10.00,14.2100,34.745,69.0825,413.21
34,IN,skrill,success,622.0,52.926945,49.277367,10.00,14.4650,37.170,72.2625,264.25
35,IN,upi,cancel,56.0,54.866964,46.513109,10.00,16.3375,41.560,85.1275,224.03
36,IN,upi,pending,10806.0,51.260508,49.890207,10.00,14.1500,34.495,70.1100,496.68
37,IN,upi,success,7662.0,50.980792,48.044340,10.00,14.5400,34.680,70.8275,394.90
38,PK,binance_pay,cancel,13235.0,51.473931,50.014483,10.00,14.2000,34.670,70.2100,448.71
39,PK,binance_pay,pending,19.0,55.126316,53.805632,10.00,14.6500,45.660,66.8350,212.46
40,PK,binance_pay,success,1361.0,50.295393,46.092489,10.00,14.9600,36.670,69.2100,360.22
41,PK,card_processing,cancel,18340.0,50.555558,48.889617,10.00,14.4300,34.800,68.5425,606.68
42,PK,card_processing,pending,153.0,51.851895,49.899489,10.00,13.2900,34.950,73.3400,284.45
43,PK,card_processing,success,21233.0,50.859654,49.043025,10.00,14.3900,34.530,69.5900,482.28
44,PK,jazzcash,cancel,51778.0,51.000195,49.442204,10.00,14.3900,34.670,69.4000,591.93
45,PK,jazzcash,pending,4401.0,50.558739,47.764041,10.00,14.5700,34.270,69.5000,372.92
46,PK,jazzcash,success,1706.0,51.090006,50.140057,10.00,14.6500,34.505,67.5125,404.39
47,PK,skrill,pending,6536.0,50.578571,48.423868,10.00,14.3050,34.730,69.6325,406.97
48,PK,skrill,success,625.0,49.484640,50.562021,10.00,13.6600,30.960,65.3600,483.38
49,SA,binance_pay,cancel,84801.0,51.034993,49.552476,10.00,14.3000,34.670,69.6100,625.74
50,SA,binance_pay,pending,123.0,50.323252,49.062399,10.00,14.6400,33.630,70.2650,263.49
51,SA,binance_pay,success,9127.0,51.273605,49.348705,10.00,14.7600,34.520,70.4000,598.23
52,SA,card_processing,cancel,120074.0,50.818172,49.044585,10.00,14.3000,34.665,69.3600,815.13
53,SA,card_processing,pending,1135.0,51.751965,50.437150,10.00,13.9500,35.070,72.3150,438.34
54,SA,card_processing,success,137672.0,51.031756,49.093191,10.00,14.5700,34.890,69.1825,579.11
55,SA,skrill,pending,43087.0,50.852787,49.213598,10.00,14.3400,34.630,68.9950,583.69
56,SA,skrill,success,4109.0,51.495388,49.250937,10.00,14.9600,35.240,69.9500,417.85
57,TR,binance_pay,cancel,6522.0,49.970837,48.927185,10.00,14.0150,33.460,68.1675,525.77
58,TR,binance_pay,pending,8.0,33.570000,25.321358,10.00,10.0000,27.155,53.7725,74.40
59,TR,binance_pay,success,646.0,48.288467,47.833205,10.00,12.6225,31.090,68.4650,439.39
60,TR,card_processing,cancel,8939.0,51.233723,49.952513,10.00,15.0100,35.100,69.2850,542.41
61,TR,card_processing,pending,86.0,56.257442,61.884069,10.00,12.9300,33.030,75.7450,345.39
62,TR,card_processing,success,10423.0,51.577582,49.696045,10.00,14.4950,34.930,70.6450,471.05
63,TR,skrill,pending,3255.0,50.575834,48.164276,10.00,14.6100,34.000,69.6300,397.22
64,TR,skrill,success,297.0,51.080202,46.236012,10.00,16.4400,40.490,68.0500,272.89
65,ZA,binance_pay,cancel,4389.0,50.319581,48.006530,10.00,14.8000,34.710,68.2400,515.65
66,ZA,binance_pay,pending,5.0,63.096000,44.681717,15.62,23.8800,61.890,94.2100,119.88
67,ZA,binance_pay,success,489.0,49.640327,46.948893,10.00,13.9600,33.600,67.2700,294.22
68,ZA,card_processing,cancel,5961.0,50.920406,49.896102,10.00,14.0900,34.430,69.0900,539.65
69,ZA,card_processing,pending,58.0,58.096552,51.222815,10.00,18.3700,43.350,72.4025,228.99
70,ZA,card_processing,success,6986.0,50.637459,48.666442,10.00,14.4850,35.120,68.5375,423.54
71,ZA,skrill,pending,2181.0,50.252568,48.090232,10.00,13.7300,34.530,70.2800,390.66
72,ZA,skrill,success,209.0,47.691627,41.711283,10.00,15.0600,33.770,65.8000,204.03

In [12]:
bills.loc[:, ['amount']].describe().transpose()

            count       mean        std   min    25%    50%   75%     max
amount  1000000.0  50.935791  49.159379  10.0  14.39  34.68  69.4  815.13

Статистически всё преимущественно ровно, некоторое сильные девиации можно объяснить низким числом ивентом (например, `ZA-binance_pay-pending` 75% __94__ против обычного 69, но их всего лишь 5), а некоторые нет (`ZA-binance_pay-pending` 75% __34.7__ из 4389 ивентов)

In [13]:
categories = ('payment_method', 'status', 'country')

for cat in categories:
    print(bills[cat].value_counts(), '\n')

payment_method
card_processing    547390
binance_pay        184078
skrill              99472
jazzcash            57885
nagad               32965
paytm               32736
pix                 26950
upi                 18524
Name: count, dtype: int64

status
cancel     495339
success    348188
pending    156473
Name: count, dtype: int64

country
SA    400128
AE    200510
PK    119387
IN     99048
BD     79526
BR     50947
TR     30176
ZA     20278
Name: count, dtype: int64

In [14]:
bills.loc[:, ['country', 'payment_method']].value_counts().sort_index()

country  payment_method
AE       binance_pay         46882
         card_processing    130057
         skrill              23571
BD       binance_pay         10886
         card_processing     30232
         nagad               32965
         skrill               5443
BR       binance_pay          5585
         card_processing     15609
         pix                 26950
         skrill               2803
IN       card_processing     40432
         paytm               32736
         skrill               7356
         upi                 18524
PK       binance_pay         14615
         card_processing     39726
         jazzcash            57885
         skrill               7161
SA       binance_pay         94051
         card_processing    258881
         skrill              47196
TR       binance_pay          7176
         card_processing     19448
         skrill               3552
ZA       binance_pay          4883
         card_processing     13005
         skrill               2390
Name: count, dtype: int64

In [15]:
bills['event_date'] = bills['event_datetime'].dt.date
bills['event_date'].value_counts().sort_index()

event_date
2022-12-01    33334
2022-12-02    33333
2022-12-03    33333
2022-12-04    33334
2022-12-05    33333
2022-12-06    33333
2022-12-07    33334
2022-12-08    33333
2022-12-09    33333
2022-12-10    33333
2022-12-11    33334
2022-12-12    33333
2022-12-13    33333
2022-12-14    33334
2022-12-15    33333
2022-12-16    33333
2022-12-17    33334
2022-12-18    33333
2022-12-19    33333
2022-12-20    33333
2022-12-21    33334
2022-12-22    33333
2022-12-23    33333
2022-12-24    33334
2022-12-25    33333
2022-12-26    33333
2022-12-27    33334
2022-12-28    33333
2022-12-29    33333
2022-12-30    33333
2022-12-31        1
Name: count, dtype: int64

In [16]:
bills.loc[bills['event_date']==date(2022, 12, 31), :]

,event_datetime,user_id,payment_method,country,amount,status,event_date
999999,2022-12-31,4105705,card_processing,SA,129.44,success,2022-12-31

In [17]:
bills_30 = bills.loc[bills['event_date']==date(2022, 12, 30), :].sort_values('event_datetime')

bills_30.head()

,event_datetime,user_id,payment_method,country,amount,status,event_date
966666,2022-12-30 00:00:00.777600777,7915968,binance_pay,PK,10.00,cancel,2022-12-30
966667,2022-12-30 00:00:03.369603369,3510853,card_processing,SA,23.59,cancel,2022-12-30
966668,2022-12-30 00:00:05.961605961,9435216,card_processing,SA,10.00,success,2022-12-30
966669,2022-12-30 00:00:08.553608553,4494745,card_processing,AE,28.64,cancel,2022-12-30
966670,2022-12-30 00:00:11.145611145,9908360,card_processing,AE,14.76,success,2022-12-30

In [18]:
bills_30.tail()

,event_datetime,user_id,payment_method,country,amount,status,event_date
999994,2022-12-30 23:59:47.039987040,4434027,card_processing,SA,44.87,cancel,2022-12-30
999995,2022-12-30 23:59:49.631989632,9064597,card_processing,SA,43.76,success,2022-12-30
999996,2022-12-30 23:59:52.223992224,3323918,pix,BR,159.32,success,2022-12-30
999997,2022-12-30 23:59:54.815994816,9937162,skrill,SA,127.25,pending,2022-12-30
999998,2022-12-30 23:59:57.407997408,9489398,card_processing,SA,10.00,cancel,2022-12-30

Видимо, всё упало 2022-12-31 (скорее всего, единственная запись в 0:00:00 больше относилась к предыдущему дню).

Посмотрим, единственная ли это проблема. "Нужно видеть не только то, что в данных есть, но и чего в них нет" — проверим, все ли осмысленные комбинации присутствуют.

Я бы хотел __каждый день__ видеть:
- все статусы,
- все пары страна-метод_оплаты (а не просто "все страны и все методы оплаты", потому что некоторые методы могут быть недоступны в некоторых странах).

In [19]:
all_statuses = pd.DataFrame(bills['status'].unique(), columns=['status', ])
all_dates = pd.DataFrame(bills['event_date'].unique(), columns=['event_date', ])

bills_cmb = (
    bills
    .loc[:, ['country', 'payment_method']]
    .value_counts().reset_index()
    .merge(
        right=all_statuses,
        how='cross'
    )
    .merge(
        right=all_dates,
        how='cross'
    )
    .loc[: , ['country', 'payment_method', 'status', 'event_date']]
)

bills_cmb

     country   payment_method   status  event_date
0         SA  card_processing  success  2022-12-01
1         SA  card_processing  success  2022-12-02
2         SA  card_processing  success  2022-12-03
3         SA  card_processing  success  2022-12-04
4         SA  card_processing  success  2022-12-05
...      ...              ...      ...         ...
2599      ZA           skrill  pending  2022-12-27
2600      ZA           skrill  pending  2022-12-28
2601      ZA           skrill  pending  2022-12-29
2602      ZA           skrill  pending  2022-12-30
2603      ZA           skrill  pending  2022-12-31

[2604 rows x 4 columns]

In [20]:
bills_all = (
    bills_cmb
    .merge(
        right=bills,
        how='left',
        on=['country', 'payment_method', 'status', 'event_date']
    )
)

bills_all.head()

,country,payment_method,status,event_date,event_datetime,user_id,amount
0,SA,card_processing,success,2022-12-01,2022-12-01 00:00:12.960012960,9019766.0,52.13
1,SA,card_processing,success,2022-12-01,2022-12-01 00:00:25.920025920,3886551.0,35.76
2,SA,card_processing,success,2022-12-01,2022-12-01 00:00:44.064044064,3713155.0,10.00
3,SA,card_processing,success,2022-12-01,2022-12-01 00:01:12.576072576,5481180.0,64.60
4,SA,card_processing,success,2022-12-01,2022-12-01 00:01:15.168075168,8140859.0,324.62

In [21]:
bills_all['has_missing'] = bills_all['amount'].isna()

# bills_all.groupby(['country', 'payment_method', 'status', 'event_date'])['amount'].isna().sum()
bills_all['has_missing'].value_counts()

has_missing
False    1000000
True         554
Name: count, dtype: int64

In [22]:
#Добавили 554 комбинации, которых не было в оригинальном файле.

bills_missing = (
    bills_all
    .groupby(['payment_method', 'status', 'event_date'], observed=True) #'country', 'status',
    ['has_missing'].min()
    .reset_index()
)

#Если оставить 2022-12-31, то смысла в выводе не будет — там не хватает всех.
(
    bills_missing
    .loc[
        (bills_missing['has_missing'] > 0) & (bills_missing['event_date'] != date(2022, 12, 31)),
        'payment_method'
    ].unique()
)

['nagad', 'skrill', 'upi']
Categories (8, object): ['binance_pay', 'card_processing', 'jazzcash', 'nagad', 'paytm', 'pix', 'skrill', 'upi']

In [23]:
#Дальше проверю в Tableau, там удобнее переключать фильтры в UI.
# bills_all.to_csv('./data/bills_all.csv')

### Ответ

__Главная проблема__: всё упало __2022-12-31__ — в эту дату пришёл один платёж, причём он, видимо, задержался с предыдущего дня.

__Другие важные проблемы:__
1. `binance_pay` из `AE` имеет __100%__ отказов на всём промежутке (нет ни `pending`, ни `success` ивентов),  для остальных стран процент `cancel` стабильно __90%__ (что очень плохо).
2. У `nagad` и `skrill` вообще нет `cancel` ивентов на всём промежутке, __90%+__ `pending`. Возможно, это фича (или вообще очень хорошо, не нашёл на их сайтах), но настораживает.
3. У `upi` нет `cancel` ивентов c __2022-12-03__. Так как они когда-то были, гораздо менее вероятно, что это хорошо, гораздо более вероятно, что что-то сломалось и эти ивенты не доходят.

_Менее важные проблемы:_
1. У `binance_pay` ежедневно стабильно около __93%__ ивентов `cancel` — возможно, это фича.
2. У `binance_pay` и `card_processing` почти нет `pending` ивентов, что хорошо, потому что чем меньше, тем лучше, но при этом они есть, так что данные (скорее всего) идут — хотя есть дни, в которые из некоторых стран их не было, например, для `binance_pay`: __BR__ до 2022-12-19; __PK__ между 2022-12-02 и 2022-12-18; __TR__ между 2022-12-09 и 2022-12-21.

Остальные данные, даже если выглядят не особо красиво, соответствуют некоторому паттерну (девиации подневных сумм по статусам от средней суммы по всем дням незначительны) — до __2022-12-31__.

## Решение2

>во 2 немного доделать. статусы можно рассматривать как success и не success, а не 3 варианта \
>pending и cancel - это одно и то же (non-success)

### Код

In [24]:
bills['is_success'] = bills['status'] == 'success'

bills['is_success'].value_counts()

is_success
False    651812
True     348188
Name: count, dtype: int64

In [25]:
bills_stats = (
    bills
    .groupby(['country', 'payment_method', 'is_success'], observed=True)
    ['amount'].describe()
    .reset_index()
    .sort_values(['country', 'payment_method', 'is_success'])
)

pd.options.display.max_rows = bills_stats.shape[0]
bills_stats

,country,payment_method,is_success,count,mean,std,min,25%,50%,75%,max
0,AE,binance_pay,False,46882.0,51.000850,49.114783,10.0,14.4300,34.740,69.6300,515.48
1,AE,card_processing,False,60823.0,50.439023,48.541424,10.0,14.3550,34.250,68.7950,575.57
2,AE,card_processing,True,69234.0,51.105877,49.233498,10.0,14.2300,34.710,69.7900,550.82
3,AE,skrill,False,21507.0,51.056879,49.107822,10.0,14.5950,34.880,70.0300,583.22
4,AE,skrill,True,2064.0,51.049283,47.810847,10.0,14.8100,35.550,68.9725,318.25
5,BD,binance_pay,False,9797.0,50.985350,49.742764,10.0,14.3400,34.230,68.5800,700.36
6,BD,binance_pay,True,1089.0,53.123747,50.721211,10.0,12.1900,36.320,74.9600,414.09
7,BD,card_processing,False,14124.0,51.189124,50.159703,10.0,14.0575,34.700,69.7100,523.29
8,BD,card_processing,True,16108.0,50.691772,48.857772,10.0,14.5100,34.295,68.7925,460.99
9,BD,nagad,False,31445.0,50.981948,49.189687,10.0,14.4100,34.790,69.2300,456.98
10,BD,nagad,True,1520.0,50.292855,48.297416,10.0,12.0225,32.800,71.5700,325.20
11,BD,skrill,False,4979.0,51.157271,49.734220,10.0,14.4950,34.740,69.4000,496.26
12,BD,skrill,True,464.0,51.611746,48.599060,10.0,14.7200,36.225,72.4825,306.83
13,BR,binance_pay,False,5069.0,51.248769,49.538801,10.0,15.2000,35.490,68.3800,525.14
14,BR,binance_pay,True,516.0,49.078915,47.295952,10.0,14.8300,30.570,65.7675,274.80
15,BR,card_processing,False,7337.0,50.796072,49.996438,10.0,14.2400,34.190,69.3900,507.37
16,BR,card_processing,True,8272.0,50.736142,48.675936,10.0,14.5650,34.855,69.0350,556.75
17,BR,pix,False,12720.0,52.087028,49.881760,10.0,14.7400,35.255,71.2700,399.02
18,BR,pix,True,14230.0,50.667329,49.441715,10.0,14.1025,34.355,69.1150,526.34
19,BR,skrill,False,2560.0,53.549172,51.668748,10.0,14.6350,37.540,73.4875,530.42
20,BR,skrill,True,243.0,53.073786,56.528934,10.0,12.9500,32.240,71.6850,324.61
21,IN,card_processing,False,19087.0,51.111340,48.963440,10.0,14.6350,35.080,69.3600,490.04
22,IN,card_processing,True,21345.0,50.299510,48.621902,10.0,14.1000,34.030,68.7200,811.84
23,IN,paytm,False,22800.0,51.262291,49.248167,10.0,14.4000,35.160,70.3050,622.05
24,IN,paytm,True,9936.0,50.257662,48.591948,10.0,14.4100,34.035,68.2525,483.15
25,IN,skrill,False,6734.0,50.386726,47.890218,10.0,14.2100,34.745,69.0825,413.21
26,IN,skrill,True,622.0,52.926945,49.277367,10.0,14.4650,37.170,72.2625,264.25
27,IN,upi,False,10862.0,51.279101,49.872053,10.0,14.1500,34.545,70.2100,496.68
28,IN,upi,True,7662.0,50.980792,48.044340,10.0,14.5400,34.680,70.8275,394.90
29,PK,binance_pay,False,13254.0,51.479167,50.018131,10.0,14.2000,34.685,70.2000,448.71
30,PK,binance_pay,True,1361.0,50.295393,46.092489,10.0,14.9600,36.670,69.2100,360.22
31,PK,card_processing,False,18493.0,50.566283,48.896823,10.0,14.4200,34.800,68.5700,606.68
32,PK,card_processing,True,21233.0,50.859654,49.043025,10.0,14.3900,34.530,69.5900,482.28
33,PK,jazzcash,False,56179.0,50.965612,49.312529,10.0,14.4100,34.640,69.4200,591.93
34,PK,jazzcash,True,1706.0,51.090006,50.140057,10.0,14.6500,34.505,67.5125,404.39
35,PK,skrill,False,6536.0,50.578571,48.423868,10.0,14.3050,34.730,69.6325,406.97
36,PK,skrill,True,625.0,49.484640,50.562021,10.0,13.6600,30.960,65.3600,483.38
37,SA,binance_pay,False,84924.0,51.033962,49.551491,10.0,14.3000,34.670,69.6100,625.74
38,SA,binance_pay,True,9127.0,51.273605,49.348705,10.0,14.7600,34.520,70.4000,598.23
39,SA,card_processing,False,121209.0,50.826916,49.057677,10.0,14.3000,34.670,69.3800,815.13
40,SA,card_processing,True,137672.0,51.031756,49.093191,10.0,14.5700,34.890,69.1825,579.11
41,SA,skrill,False,43087.0,50.852787,49.213598,10.0,14.3400,34.630,68.9950,583.69
42,SA,skrill,True,4109.0,51.495388,49.250937,10.0,14.9600,35.240,69.9500,417.85
43,TR,binance_pay,False,6530.0,49.950744,48.907594,10.0,14.0100,33.460,68.1450,525.77
44,TR,binance_pay,True,646.0,48.288467,47.833205,10.0,12.6225,31.090,68.4650,439.39
45,TR,card_processing,False,9025.0,51.281594,50.077782,10.0,14.9900,35.100,69.3800,542.41
46,TR,card_processing,True,10423.0,51.577582,49.696045,10.0,14.4950,34.930,70.6450,471.05
47,TR,skrill,False,3255.0,50.575834,48.164276,10.0,14.6100,34.000,69.6300,397.22
48,TR,skrill,True,297.0,51.080202,46.236012,10.0,16.4400,40.490,68.0500,272.89
49,ZA,binance_pay,False,4394.0,50.334119,48.000075,10.0,14.8125,34.710,68.2475,515.65
50,ZA,binance_pay,True,489.0,49.640327,46.948893,10.0,13.9600,33.600,67.2700,294.22
51,ZA,card_processing,False,6019.0,50.989556,49.909614,10.0,14.1050,34.500,69.2450,539.65
52,ZA,card_processing,True,6986.0,50.637459,48.666442,10.0,14.4850,35.120,68.5375,423.54
53,ZA,skrill,False,2181.0,50.252568,48.090232,10.0,13.7300,34.530,70.2800,390.66
54,ZA,skrill,True,209.0,47.691627,41.711283,10.0,15.0600,33.770,65.8000,204.03

После перехода на бинарные статусы все, кроме максимумов (и 75% `BD-binance_pay-True`), стало статистически эквивалентным.

In [26]:
all_successes = pd.DataFrame([True, False], columns=['is_success', ])
# Надежнее было бы взять весь декабрь из скелета календаря, а не (если в них чего-то нет, то упустили бы), но в этом случае разницы нет.
all_dates = pd.DataFrame(bills['event_date'].unique(), columns=['event_date', ])

bills_cmb = (
    bills
    .loc[:, ['country', 'payment_method']]
    .value_counts().reset_index()
    .merge(
        right=all_successes,
        how='cross'
    )
    .merge(
        right=all_dates,
        how='cross'
    )
    .loc[: , ['country', 'payment_method', 'is_success', 'event_date']]
)
bills_cmb

     country   payment_method  is_success  event_date
0         SA  card_processing        True  2022-12-01
1         SA  card_processing        True  2022-12-02
2         SA  card_processing        True  2022-12-03
3         SA  card_processing        True  2022-12-04
4         SA  card_processing        True  2022-12-05
...      ...              ...         ...         ...
1731      ZA           skrill       False  2022-12-27
1732      ZA           skrill       False  2022-12-28
1733      ZA           skrill       False  2022-12-29
1734      ZA           skrill       False  2022-12-30
1735      ZA           skrill       False  2022-12-31

[1736 rows x 4 columns]

In [27]:
bills_all = (
    bills_cmb
    .merge(
        right=bills,
        how='left',
        on=['country', 'payment_method', 'is_success', 'event_date']
    )
)

bills_all.head()

,country,payment_method,is_success,event_date,event_datetime,user_id,amount,status
0,SA,card_processing,True,2022-12-01,2022-12-01 00:00:12.960012960,9019766.0,52.13,success
1,SA,card_processing,True,2022-12-01,2022-12-01 00:00:25.920025920,3886551.0,35.76,success
2,SA,card_processing,True,2022-12-01,2022-12-01 00:00:44.064044064,3713155.0,10.00,success
3,SA,card_processing,True,2022-12-01,2022-12-01 00:01:12.576072576,5481180.0,64.60,success
4,SA,card_processing,True,2022-12-01,2022-12-01 00:01:15.168075168,8140859.0,324.62,success

In [28]:
bills_all['has_missing'] = bills_all['amount'].isna()

# bills_all.groupby(['country', 'payment_method', 'status', 'event_date'])['amount'].isna().sum()
bills_all['has_missing'].value_counts()

has_missing
False    1000000
True          85
Name: count, dtype: int64

In [29]:
#Добавили 85 комбинаций, которых не было в оригинальном файле.

bills_missing = (
    bills_all
    .groupby(['payment_method', 'is_success', 'event_date'], observed=True) #'country', 'status',
    ['has_missing'].min()
    .reset_index()
)

#Если оставить 2022-12-31, то смысла в выводе не будет — там не хватает всех.
#А если не оставить, новый вывод пустой.
(
    bills_missing
    .loc[
        (bills_missing['has_missing'] > 0) & (bills_missing['event_date'] != date(2022, 12, 31)),
        'payment_method'
    ].unique()
)

[], Categories (8, object): ['binance_pay', 'card_processing', 'jazzcash', 'nagad', 'paytm', 'pix', 'skrill', 'upi']

In [30]:
#Дальше проверю в Tableau, там удобнее переключать фильтры в UI.
#bills_all.to_csv('./data/bills_all2.csv')

### Ответ

__Главная проблема__ не изменилась: всё упало __2022-12-31__ — в эту дату пришёл один платёж, причём он, видимо, задержался с предыдущего дня.

__Другие важные проблемы:__

_Disclaimer:_ Указанные проценты показывают часть суммы `amount` для `success/non-success` от общей суммы, так как это кажется более адекватной мерой, чем `count`. Проценты не отличаются за исключением `skrill` — вместо __90%__ `non-success` будет __91%__.

1. `binance_pay` ежедневно имеет около __93%__ `non-success` ивентов, причем из `AE` — __100%__ на всём промежутке.
2. `jazzcash` имеет __97%__ `non-success` ивентов на всём промежутке (всё из __PK__).
3. `nagad` имеет __95%__ `non-success` ивентов на всём промежутке (всё из __BD__).
4. `skrill` имеет около __90%__ `non-success` ивентов на всём промежутке (много стран, везде приблизительно такой процент).

Из _позитивного_ хочется отметить:
1. `paytm` приемлем — __30%__ `success` (ниже средних по выборке __35%__).
2. `upi` хорош — __41%__ `success` (немногим выше среднего по выборке).
3. `card_processing` и `pix` прекрасны — __53%__ и __52%__ `success` (намного выше среднего по выборке, лучшие здесь).

"Feedback":

>- найдено 2 из 3 аномалий
>- ожидались временные графики
>- ожидалось применение какого-либо алгоритма детекции аномалий
>- задача на sql решена не с первого раза
>
>в целом, решение не плохое и мы предусматриваем погрешности в решении, и на основные наши специализации аналитиков такое подходит,
>но вакансия на платежного аналитика -  она более высокого уровня"

# Бонус. Парадокс Симпсона

## Официальное Условие

Исследуется польза введения новой учебной программы в университете для первокурсников.
Оценка эффективности проводится по результатам одного экзамена в конце года с оценкой сдал/не сдал.
Экзамен не менялся, менялась только учебная программа.
Считается что результативность экзамена - хороший показатель эффективности учебной программы.
Исследование проводится по 2 годам. 1 - до введения. 2 - когда программа была введена.
Оба года принималось одинаковое число студентов.
Среди студентов второго года нет тех кто учился и в первый год.
Предполагается что в конце года все поступившие студенты участвовали в экзамене.
 
Результаты поступили в следующем виде: 
1. Общая успешност сдачи экзамена - снизилась.
2. Успешность сдачи экзамена у мужчин выросла. У женщин - также выросла. 
 
Вопросы: 
1. Как такое может быть?
2. Какие можно сделать выводы о пользе нововведения?
Объяснения нужно дать для условного деканата, который со понятиями статистики и теории вероятностей не знаком.

## Условие

Есть университет, в котором обучаются люди двух классов: A и B. Успех каждого студента определяется результатом экзамена — зачет или незачет. Экзамен является точной оценкой успеваемости студента. Студентов достаточно, чтобы обеспечить статистически значимые результаты.

В прошлом году __60%__ студентов получили зачет.

В этом году университет обновил программу. Процент успеха в обоих классах вырос, но общий показатель упал до __50%__.

1. Как такое возможно? (Нельзя просто назвать имя феномена, нужно объяснить.)
2. Должен ли университет откатиться к прошлой программе или продолжать с текущей?

## Математическая формулировка

[Парадокс Симпсона](https://en.wikipedia.org/wiki/Simpson%27s_paradox) во всей красе _(только этого мало)_. Распишем конверсию из попытки студента сдать экзамен в зачет: каждый студент пытается сдать экзамен, у него или нее это получается в зависимости от класса и программы:

$$ C=\frac{S}{N}=\frac{\sum{S_i}}{\sum{N_i}}=\frac{\sum{C_i \cdot N_i}}{\sum{N_i}}$$

В случае двух классов A и B получаем:

$$ C=\frac{C_A \cdot N_A + C_B \cdot N_B}{N_A + N_B}$$

$$ wlg \; C_A \leq C_B : $$
$$ C_B = C_A + u, \;\; 0 \leq u \leq 1 - C_A $$

Почему $wlg$? Потому что если $C_A \geq C_B$, то мы просто меняем индексы и оказываемся в той же ситуации.

Для простоты положим, что $N$ не меняется между годами ("примем пропускную способность университета приблизительно постоянной"). Тогда:
$$C=\frac{C_A \cdot N_A + C_B \cdot N_B}{N_A + N_B}=\frac{C_A \cdot N_A + (C_A + u) \cdot (N - N_A)}{N_A + N - N_A}=$$
$$=\frac{C_A \cdot N_A + C_A \cdot N + u \cdot N - C_A \cdot N_A - u \cdot N_A}{N}=\frac{C_A \cdot N + u \cdot (N - N_A)}{N}=$$
$$=C_A+\frac{N - N_A}{N} \cdot u$$

Рассмотрим краевые случаи:
$$N_A=N: \;\; C=C_A+\frac{N - N}{N} \cdot u = C_A$$
$$N_A=0: \;\; C=C_A+\frac{N - 0}{N} \cdot u = C_A + u = C_B$$

Получаем, что общая конверсия $C$ принадлежит интервалу $(C_A, C_B)$. Именно __интервалу__, а не отрезку, так как у нас есть два класса с __ненулевыми__ размерами, а особенный случай $C_A=C_B=C$ иррелевантен в этой задаче, потому что невозможно найти такую пару лет ($C^i$ есть конверсия в год $i$), при которых:
$$
\begin{cases}
C_A^2 > C_A^1 \\
C_B^2 > C_B^1 \\
C^2 < C^1 \\
\end{cases}
$$
Потому что это равносильно
$$
\begin{cases}
C^2 > C_A^1 \\
C^2 > C_B^1 \\
C^2 < C^1 \\
\end{cases}
$$
А, как показано выше, $\forall i \; C_A^i \leq C^i \leq C_B^i$, засим получаем противоречие:
- конверсия второго года больше верхней границы конверсии первого года: $C^2 > C_B^1 \geq C^1 \rightarrow C^2 > C^1$,
- но при этом меньше самой конверсии первого года $C^2 < C^1$.

Поэтому в этой задаче:
$$\forall i \;\; C_A^i < C^i < C_B^i$$

Возможна даже ситуация, при которой средние стали хуже в обоих подгруппах, но общее стало лучше — дисбаланс классов позволяет варьировать общую конверсию довольно сильно (хоть и в пределах групповых). Это напомнило мне [видео 3blue1brown "The medical test paradox, and redesigning Bayes' rule"](https://youtu.be/lG4VkPoG3ko?list=PLiAulSm0XXgvCGe63mrAkda9UQ9478YQv&t=902):
![image](./images/b1.jpg)
![image](./images/b2.jpg)
![image](./images/b3.jpg)

Тест влияет на конверсию по классу, а не на общую. И если дисбаланс классов настолько велик, что может обнулить или даже развернуть эффект от смены контроля (программы), то проблема не в контроле, а в дизайне эксперимента: выборе метрики и/или классовом распределении.

## Численные примеры

In [31]:
N = 1_000

def calc_c(c_a, c_b, n_a, N_=N):
    n_b = N_ - n_a
    return (c_a * n_a + c_b * n_b) / N_

def calc_c_u(c_a, u, n_a, N_=N):
    """Calculate via u(plift)."""
    return calc_c(c_a, c_a+u, n_a, N_=N)


P_I = (0.40, 0.80)
P_II = (41/90, 0.90)
P_III = (0.60, 0.95)

cfg_tuples = (
    (*P_I, 500),
    (*P_II, 900),
    (*P_I, 400),
    (*P_II, 400),
    (*P_II, 950),
    (*P_III, 975),
    (*P_III, 500),
    (*P_III, 25)
)

def print_c_results(c_tuples, func):
    for i in range(len(c_tuples)):
        ct=c_tuples[i]
        print('{}: C_A={:.2%}; C_B={:.2%}; N_A={:,}; N_B={:,} -> C={:.2%}'.format(i+1, *ct, N-ct[2], func(*ct)))
        
        if i+1 in (3, 5):
            print('\n')

print_c_results(cfg_tuples, calc_c)

1: C_A=40.00%; C_B=80.00%; N_A=500; N_B=500 -> C=60.00%
2: C_A=45.56%; C_B=90.00%; N_A=900; N_B=100 -> C=50.00%
3: C_A=40.00%; C_B=80.00%; N_A=400; N_B=600 -> C=64.00%


4: C_A=45.56%; C_B=90.00%; N_A=400; N_B=600 -> C=72.22%
5: C_A=45.56%; C_B=90.00%; N_A=950; N_B=50 -> C=47.78%


6: C_A=60.00%; C_B=95.00%; N_A=975; N_B=25 -> C=60.88%
7: C_A=60.00%; C_B=95.00%; N_A=500; N_B=500 -> C=77.50%
8: C_A=60.00%; C_B=95.00%; N_A=25; N_B=975 -> C=94.12%

$1 \rightarrow 2$ — ситуация из условия.


Варианты:
- $2 \rightarrow 3$ — худший сценарий: университет в панике откатывает программу, получает лучшую общую конверсию, и, не обращая внимание на ухудшение в обоих классах, считает, что сделал все правильно (64% > 50%).
- $2 \rightarrow 4$ — хотя если бы мы остались на программе __II__, всё было бы ещё лучше (72% > 64% > 50%)!
- $2 \rightarrow 5$ — или нет... (48% < 50% < 64%) — до тех пор, пока мы не контролируем (дис)баланс классов, мы не можем гарантировать адекватное сравнение.


Даже выдающаяся программа __III__ может оказаться в ситуации, когда она еле лучше оригинальной __I__ ($2 \rightarrow 6$: 61% > 60%), хотя в балансе она намного лучше неё ($2 \rightarrow 7$: 78% > 60%), а в обратном дисбалансе намного-много лучше ($2 \rightarrow 8$: 94% > 60%).

## Предложения

### Другая метрика

Поменяем целевую метрику: рассчитаем общую конверсию как среднее между поклассовыми конверсиями (некоторое "перевзвешивание": теперь оба класса одинаково важны вне зависимости от их размеров).

In [32]:
def calc_c_avg(c_a, c_b, n_a, N_=N):
    return (c_a + c_b) / 2

print_c_results(cfg_tuples, calc_c_avg)

1: C_A=40.00%; C_B=80.00%; N_A=500; N_B=500 -> C=60.00%
2: C_A=45.56%; C_B=90.00%; N_A=900; N_B=100 -> C=67.78%
3: C_A=40.00%; C_B=80.00%; N_A=400; N_B=600 -> C=60.00%


4: C_A=45.56%; C_B=90.00%; N_A=400; N_B=600 -> C=67.78%
5: C_A=45.56%; C_B=90.00%; N_A=950; N_B=50 -> C=67.78%


6: C_A=60.00%; C_B=95.00%; N_A=975; N_B=25 -> C=77.50%
7: C_A=60.00%; C_B=95.00%; N_A=500; N_B=500 -> C=77.50%
8: C_A=60.00%; C_B=95.00%; N_A=25; N_B=975 -> C=77.50%

### Разделение

Другое возможное решение проблемы дисбаланса — разделение (сплитинг). Оставляем обе программы, разделяя на статистически равные подгруппы (как это сделали, например [Morisano, Hirsh, Peterson, Pihl, And Shore](http://individual.utoronto.ca/jacobhirsh/publications/GoalSettingJAP2010.pdf), страница 4/258) — в нашем случае это очень просто, потому что характеристика одна — класс. Тогда можно будет сравнить и погрупповые, и общее, потому что оно хоть и смещённое, но в одну и ту же сторону в обоих случаях.

In [33]:
program_tuples = (
    (P_I, P_II, 500),
    (P_I, P_II, 25),
    (P_I, P_II, 975),
    (P_II, P_I, 100),
    (P_II, P_I, 500),
    (P_II, P_I, 900),
    (P_I, P_III, 10),
    (P_I, P_III, 500),
    (P_I, P_III, 990)
)

def calc_c_split(prog_1, prog_2, n_a, func, N_=N):
    n_a1 = round(n_a / 2)
    n_a2 = n_a - n_a1

    n_b1, n_b2 = round(N_/2 - n_a1), round(N_/2 - n_a2)
    
    return (func(*prog_1, n_a1, N_=N_/2), n_a1, n_b1, func(*prog_2, n_a2, N_=N_/2), n_a2, n_b2)


def print_c_results_split(c_tuples, split_func, func):
    for i in range(len(c_tuples)):
        ct = c_tuples[i]
        res = split_func(*ct, func)
        print("""{}:
P_I:    C_A={:.2%}, C_B={:.2%};
P_II:   C_A={:.2%}, C_B={:.2%};
Sample: N_A={:,}; N_B={:,}
Totals: C_I={:.2%} (split {:,}/{:,}); C_II={:.2%} (split {:,}/{:,})
Comparison (Pre):  P_I < P_II ? A: [{}]; B: [{}]
Comparison (Post): P_I < P_II ? Total: [{}]
        """.format(
                i+1,
                *ct[0],
                *ct[1],
                ct[2],
                N-ct[2],
                *res,
                ct[0][0] < ct[1][0],
                ct[0][1] < ct[1][1],
                res[0] < res[3]
            )
        )
    print('\n')

print('>Function: calc_c')
print_c_results_split(program_tuples, calc_c_split, calc_c)

print('>Function: calc_c_avg')
print_c_results_split(program_tuples, calc_c_split, calc_c_avg)

>Function: calc_c
1:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=500; N_B=500
Totals: C_I=60.00% (split 250/250); C_II=67.78% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

2:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=25; N_B=975
Totals: C_I=79.04% (split 12/488); C_II=88.84% (split 13/487)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

3:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=975; N_B=25
Totals: C_I=40.96% (split 488/12); C_II=46.71% (split 487/13)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

4:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=100; N_B=900
Totals: C_I=85.56% (split 50/450); C_II=76.00% (split 50/450)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

5:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=500; N_B=500
Totals: C_I=67.78% (split 250/250); C_II=60.00% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

6:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=900; N_B=100
Totals: C_I=50.00% (split 450/50); C_II=44.00% (split 450/50)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

7:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=10; N_B=990
Totals: C_I=79.60% (split 5/495); C_II=94.65% (split 5/495)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

8:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=500; N_B=500
Totals: C_I=60.00% (split 250/250); C_II=77.50% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

9:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=990; N_B=10
Totals: C_I=40.40% (split 495/5); C_II=60.35% (split 495/5)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]



>Function: calc_c_avg
1:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=500; N_B=500
Totals: C_I=60.00% (split 250/250); C_II=67.78% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

2:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=25; N_B=975
Totals: C_I=60.00% (split 12/488); C_II=67.78% (split 13/487)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

3:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=45.56%, C_B=90.00%;
Sample: N_A=975; N_B=25
Totals: C_I=60.00% (split 488/12); C_II=67.78% (split 487/13)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

4:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=100; N_B=900
Totals: C_I=67.78% (split 50/450); C_II=60.00% (split 50/450)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

5:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=500; N_B=500
Totals: C_I=67.78% (split 250/250); C_II=60.00% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

6:
P_I:    C_A=45.56%, C_B=90.00%;
P_II:   C_A=40.00%, C_B=80.00%;
Sample: N_A=900; N_B=100
Totals: C_I=67.78% (split 450/50); C_II=60.00% (split 450/50)
Comparison (Pre):  P_I < P_II ? A: [False]; B: [False]
Comparison (Post): P_I < P_II ? Total: [False]

7:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=10; N_B=990
Totals: C_I=60.00% (split 5/495); C_II=77.50% (split 5/495)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

8:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=500; N_B=500
Totals: C_I=60.00% (split 250/250); C_II=77.50% (split 250/250)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

9:
P_I:    C_A=40.00%, C_B=80.00%;
P_II:   C_A=60.00%, C_B=95.00%;
Sample: N_A=990; N_B=10
Totals: C_I=60.00% (split 495/5); C_II=77.50% (split 495/5)
Comparison (Pre):  P_I < P_II ? A: [True]; B: [True]
Comparison (Post): P_I < P_II ? Total: [True]

Теперь пред- и пост-сравнения всегда сонаправлены, это как раз то, чего мы хотели.

### Вывод

И выбор другой метрики, и разделение подгрупп обеспечивают сонаправленность эффектов, что разрешает парадокс Сиспсона в конкретно взятой задаче.

У обоих предложенных решений могут (и я почти уверен, что будут) проблемы с парами программ, в которой одна __не полностью__ доминирует другую:
$$ P_{II} \;?\; P_{I}:  C_A^{P_{II}} \geq C_A^{P_I}; \;\; C_B^{P_{II}} \leq C_B^{P_{I}} $$
"but that's beyond the scope of this study" (хотя мне кажется, что неплохим решением этой проблемы будет приоритизация классов).


(Учёт confounding variable ChatGPT предлагает проводить через логистическую регрессию.)